FinalProjectRestorant/Models/Starters.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProjectRestorant.Models
{
    public class Starters
    {
        public int Id { get; set; }
        public string Image { get; set; }
        [NotMapped, Required]
        public IFormFile Photo { get; set; }
        [Required, StringLength(maximumLength: 100)]
        public string BigMenuFoodName { get; set; }
        [Required, StringLength(maximumLength: 225)]
        public string Ingredient { get; set; }
        [Required, StringLength(maximumLength: 100)]
        public string Servis { get; set; }
        [Required]
        public double Price { get; set; }
        [Required]
        public string Pieces { get; set; }
        public Order Order { get; set; }
    }
}

FinalProjectRestorant/Areas/AdminPanel/Controllers/StarTersController.cs
using FinalProjectRestorant.DAL;
using FinalProjectRestorant.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProjectRestorant.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class StarTersController : Controller
    {
        public AppDbContext _context { get; }
        public IWebHostEnvironment _env { get; }
        public StarTersController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index()
        {
            return View(_context.starters);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Starters starters)
        {
            if (ModelState["Photo"].ValidationState == ModelValidationState.Invalid)
            {
                return View();
            }
            if (!starters.Photo.ContentType.Contains("image/"))
            {
                ModelState.AddModelError("Photo", "Please enter image format");
                return View();
            }
            if (starters.Photo.Length / 1024 > 500)
            {
                ModelState.AddModelError("Photo", "image size must be less 500kb");
                return View();
            }
            string fileName = Guid.NewGuid().ToString() + starters.Photo.FileName;
            string resulPath = Path.Combine(_env.WebRootPath, "photos", "Menu-photo", fileName);
            using (FileStream fileStream = new FileStream(resulPath, FileMode.Create))
            {
                await starters.Photo.CopyToAsync(fileStream);
            }
            starters.Image = fileName;
            _context.starters.Add(starters);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        //update is start
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
                return NotFound();
            var breakFast = await _context.starters.FirstOrDefaultAsync(st => st.Id == id);
            if (breakFast == null)
                return NotFound();
            return View(breakFast);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, Starters starters)
        {
            if (!ModelState.IsValid)
                return View();
            if (id == null)
                return NotFound();

            if (starters == null)
                return NotFound();

            //remove old img
            string enviroment = _env.WebRootPath;
            //string folderpath = Path.Combine(enviroment, "photos", "Our-chef-photo", slides.Photo.FileName) ;
            //FileInfo oldfile = new FileInfo(folderpath);
            //if (System.IO.File.Exists(folderpath))
            //{
            //    oldfile.Delete();
            //};
            //remove end

            //new img in local folder
            string filename = Guid.NewGuid().ToString() + '-' + starters.Photo.FileName;
            string newSlider = Path.Combine(enviroment, "photos", "Menu-photo", filename);
            using (FileStream newFile = new FileStream(newSlider, FileMode.Create))
            {
                starters.Photo.CopyTo(newFile);
            }

            //new img end   
            var startersDB = await _context.starters.FirstOrDefaultAsync(st => st.Id == id);
            startersDB.Image = filename;
            startersDB.BigMenuFoodName = starters.BigMenuFoodName;
            startersDB.Ingredient = starters.Ingredient;
            startersDB.Pieces = starters.Pieces;
            startersDB.Price = starters.Price;
            startersDB.Servis = starters.Servis;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        //update is end
        //delete is start
        public IActionResult Delete(int? id)
        {
            var starters = _context.starters.FirstOrDefault(st => st.Id == id);
            _context.starters.Remove(starters);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        //delete is end
    }
}

FinalProjectRestorant/Controllers/StartersController.cs
using FinalProjectRestorant.DAL;
using FinalProjectRestorant.Models;
using FinalProjectRestorant.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProjectRestorant.Controllers
{
    public class StartersController : Controller
    {
        private readonly AppDbContext _context;
        public StartersController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int page = 1)
        {
            decimal pageItemCount = 3;
            decimal b = Math.Ceiling(_context.starters.Count() / pageItemCount);
            ViewBag.pageCount = Convert.ToInt32(b);
            ViewBag.ActivePage = page;


            List<Starters> starters = await _context.starters.OrderBy(st => st.Id)
                                                                           .Skip((page - 1) * (int)pageItemCount)
                                                                           .Take((int)pageItemCount)
                                                                           .ToListAsync();

            StarTersVM starTers = new StarTersVM
            {
                slides = _context.Slides.ToList(),
                Starters = starters
            };
            return View(starTers);
        }

        public async Task<IActionResult> Detail(int? id)
        {
            var slides = await _context.Slides.ToListAsync();
            ViewBag.Slides = slides;

            var order = await _context.starters.FirstOrDefaultAsync(p => p.Id == id);
            if (order == null)
                return NotFound();

            //OrderVM orders = new OrderVM
            //{
            //    Slides = _context.Slides.ToList(),
            //    Order = await _context.SteakBigMenus.FirstOrDefaultAsync(p => p.Id == id),

            //};
            //if (orders.Order == null)
            //    return NotFound();


            return View(order);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Detail(Starters starters, int? id, string allPrice, string count)
        {
            if (id is null)
                return BadRequest();

            var slides = await _context.Slides.ToListAsync();
            ViewBag.Slides = slides;

            var dbStarters = await _context.starters.FirstOrDefaultAsync(p => p.Id == id);
            if (dbStarters == null)
                return NotFound();

            AdminOrder adminOrder = new AdminOrder
            {
                Image = dbStarters.Image,
                NameOfFood = dbStarters.BigMenuFoodName,
                Price = Convert.ToDouble(allPrice),
                Count = Convert.ToInt32(count)
            };
            _context.AdminOrders.Add(adminOrder);
            await _context.SaveChangesAsync();
            //Home sehifeye qayidacag burani fix edersen sonra;
            return RedirectToAction("Index", "Menu");
        }
    }
}

FinalProjectRestorant/Views/Starters/Detail.cshtml
@model Starters
@{
    ViewData["Title"] = "SteakDetail";
    List<Slides> slides = ViewBag.Slides;
}
<section class="showcase">
    <div class="video-container">
        <div class="video">
            <img src="~/../photos/Our-chef-photo/@slides.ElementAt(4).Image" alt="">
        </div>
    </div>
</section>

<div class="container ">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12 text-center">
            <div>
                <section class="slider-text-area">
                    <div class="slider-text">
                        <h5 data-aos="fade-down">@slides.ElementAt(4).Saw</h5>
                        <h2 data-aos="fade-down">@slides.ElementAt(4).RestaurantName</h2>
                        <div class="text-area col-sm-12" data-aos="fade-down">
                            <p>
                                @slides.ElementAt(4).Description
                            </p>
                        </div>
                        <a href="#" class="btn button" data-aos="fade-down">View menu</a>
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>

<section class="general-order-side">
    <div class="container content">
        <div class="row">
            <form method="post" enctype="multipart/form-data">
                <div class=" img-side" style="width: 100%; display:flex; align-items:center; justify-content:center;">
                    <img style="height:100%" src="~/photos/Menu-photo/@Model.Image" alt="">
                </div>
                <div class=" order-side">
                    <div class="food-name">
                        <h2>@Model.BigMenuFoodName</h2>
                    </div>
                    <div class="order">

                        <i class="fas fa-minus-circle"></i>

                        <p class="count">1</p>

                        <i class="fas fa-plus-circle"></i>

                    </div>
                    <div class="food-price">
                        <p>Food price</p>
                        <input asp-for="Price" style="border:none; padding-left:25%;" class="food-price-count" />

                    </div>
                    <div class="all-price">
                        <p>All Price</p>
                        <input style="border:none; padding-left:25%; font-size:30px;" class="all-price-count" name="AllPrice" value="@Model.Price" />

                        <button type="submit" class="button">
                            Confirm
                        </button>

                    </div>
                </div>
            </form>
        </div>


    </div>
</section>

FinalProjectRestorant/Views/Starters/Index.cshtml
@model StarTersVM
@{
    ViewData["Title"] = "Index";
}

<section class="showcase">
    <div class="video-container">
        <div class="video">
            <!-- <video autoplay loop muted src="../videos/WhatsApp Video 2021-10-17 at 16.27.37.mp4"></video> -->
            <img src="~/../photos/Our-chef-photo/@Model.slides.ElementAt(2).Image" alt="">
        </div>
    </div>
</section>

<div class="container ">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12 text-center">
            <div>
                <section class="slider-text-area">
                    <div class="slider-text">
                        <h5 data-aos="fade-down">@Model.slides.ElementAt(2).Saw</h5>
                        <h2 data-aos="fade-down">@Model.slides.ElementAt(2).RestaurantName</h2>
                        <div class="text-area col-sm-12" data-aos="fade-down">
                            <p>
                                @Model.slides.ElementAt(2).Description
                            </p>
                        </div>
                        <a asp-action="Index" asp-controller="Menu" class="btn button" data-aos="fade-down">View menu</a>
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>


<section class="bigmenu">
    <div class="container content">
        <div class="row">
            <div class="col-md-12 button-side">
                <span>
                    Starters
                </span>
                <a asp-action="Index" asp-controller="Menu" class="salam"> <i class="fas fa-arrow-left"></i> Album List </a>
            </div>
        </div>
        <div class="row">
            @foreach (var st in Model.Starters)
            {
                <div class="col-md-4 big-menu-card">
                    <div class="img-box">
                        <a asp-action="Detail" asp-route-id="@st.Id">
                            <img src="../photos/Menu-photo/@st.Image" alt="">
                        </a>
                        <div class="price">
                            <p>$ @st.Price</p>
                            <p>@st.Pieces </p>
                        </div>
                    </div>

                    <div class="menu-box-write">
                        <h3>@st.BigMenuFoodName</h3>
                        <p>
                            @st.Ingredient
                        </p>
                        <hr>
                        <p>
                            Served with @st.Servis
                        </p>
                    </div>
                </div>
            }

            <br /><br />
        </div>
        <div class="row">
            <nav class="d-flex justify-content-center">
                <ul class="pagination">
                    <li class="page-item  @(ViewBag.ActivePage==1?"disabled":"")">
                        <a class="page-link" style="background-color:grey; color:white; border-color:white;" asp-route-page="@(ViewBag.ActivePage==1?ViewBag.pageCount:ViewBag.ActivePage+1)">Previous</a>
                    </li>
                    @for (int i = 1; i <= ViewBag.pageCount; i++)
                    {

                        <li class="page-item @(ViewBag.ActivePage == i ? "active":"")">
                            <a class="page-link" style="background-color:grey; color:white; border-color:white;" asp-action="Index" asp-controller="Starters" asp-route-page="@i">@i</a>
                        </li>
                    }
                    <li class="page-item @(ViewBag.ActivePage==ViewBag.pageCount?"disabled":"")">
                        <a class="page-link" style="background-color:grey; color:white; border-color:white;" asp-action="Index" asp-controller="Starters" asp-route-page="@(ViewBag.ActivePage==ViewBag.pageCount?ViewBag.pageCount:ViewBag.ActivePage+1)">Next</a>
                    </li>
                </ul>
            </nav>
        </div>

    </div>
</section>